### ISSUE TITLE
Windows Help

### ISSUE THREAD

**Issue by newoski** [FallingSnow/h265ize#140]
Opening an issue, per the ReadMe hoping for some help...

I'm on Windows 10. I've installed h265ize and just tested an encode using my Z: drive, which is a Mapped Network Drive. I get the error below. I'm a Node.js new, so any help with additional steps I need to take would be greatly appreciated... Ultimately, my goal is to convert my entire directory Z:\Input to Z:\Output. Unclear on how to define input as well as the path formatting for Node.js

C:\Windows\System32>h265ize -v -d Z:\Input -q 22 -m slow
[h265ize]: [verbose] Handling keypresses...
[h265ize]: [verbose] Setting as-preset options...
[h265ize]:
        - message: EPERM: operation not permitted, stat 'C:\Windows\System32\config'
        - stack: Error: EPERM: operation not permitted, stat 'C:\Windows\System32\config'
        - errno: -4048
        - code: EPERM
        - syscall: stat
        - path: C:\Windows\System32\config
[h265ize]: [verbose] Cleaning up temp files...
[h265ize]: Process exited.

**Comment by Wxfisch** [comment]
I am also getting the same issue on Windows 10 with a network drive.

**Comment by theg1nger** [comment]
Also seeing the same issue with Windows 10

`------------------------------------------------------------------------------------------------------------------------
[h265ize]: [verbose] Encoding started at Wed, 8:13 PM
[h265ize]: [verbose] Getting metadata...
[h265ize]: [verbose] Resolving video streams...
[h265ize]: [verbose] Upconverting...
[h265ize]: [verbose] Setting video bit depth...
[h265ize]: [verbose] Mapping streams...
[h265ize]: [alert] Audio does not have a title. Title set to "Norwegian AC3 (5.1 Channel)".
[h265ize]: Norwegian
[h265ize]: [alert] Subtitle does not have a title. Title set to Norwegian.
[h265ize]: [verbose] Detecting auto crop...
[h265ize]: Crop Detection: 12/12
[h265ize]: [verbose] Mapping HE Audio streams...
[h265ize]: [verbose] Setting ffmpeg settings...
[h265ize]: [verbose] Encoding video...
[h265ize]: ffmpeg exited with code 1:
[h265ize]: [verbose] Finished encoding at Wed, 8:13 PM (a few seconds)
[h265ize]: Folder encoding finished at Wednesday, February 19th 2020, 8:13:23 PM`

**Comment by FallingSnow** [comment]
Can you guys try running this with the `--debug` flag?

**Comment by Nennivus** [comment]
I've been seeing the same, here is the output with --debug
h265ize --debug -v -d /transcode 'Cargo (2018).avi'
[h265ize]: [debug] Log file location: S:\02-movies\h265ize.log
[h265ize]: [verbose] Handling keypresses...
[h265ize]: [verbose] Setting as-preset options...
[h265ize]: Processing Cargo (2018).avi...
------------------------------------------------------------------------------------------------------------------------
[h265ize]: [verbose] Encoding started at Fri, 10:49 PM
[h265ize]: [debug] Path: Cargo (2018).avi
[h265ize]: [verbose] Getting metadata...
[h265ize]: [debug] Container data:
        - duration: 01:44:08
        - size: 1.36 GB
[h265ize]: [verbose] Resolving video streams...
[h265ize]: [debug] Working on stream:
[h265ize]: [debug] Working on stream: 1
[h265ize]: [verbose] Upconverting...
[h265ize]: [debug] Upconverting 0 tracks.
[h265ize]: [verbose] Setting video bit depth...
[h265ize]: [verbose] Mapping streams...
[h265ize]: [debug] Video stream 0:0 mapped.
        - size: 720x304
        - codec: MPEG-4 part 2
        - profile: Advanced Simple Profile
        - bit depth: 8
[h265ize]: [alert] Audio does not have a title. Title set to "Unknown AC3 (5.1 Channel)".
[h265ize]: [debug] Audio stream 0:1 mapped.
        - title: undefined
        - language: Unknown
        - codec: ATSC A/52A (AC-3)
        - channels: 6
        - profile: unknown
[h265ize]: [verbose] Detecting auto crop...
[h265ize]: Crop Detection: 1/12
[h265ize]: [debug] Running Query: ffmpeg -ss 5767.735383692308 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 2/12
[h265ize]: [debug] Running Query: ffmpeg -ss 5287.090768384615 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 3/12
[h265ize]: [debug] Running Query: ffmpeg -ss 4806.446153076923 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 4/12
[h265ize]: [debug] Running Query: ffmpeg -ss 4325.801537769231 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 5/12
[h265ize]: [debug] Running Query: ffmpeg -ss 3845.156922461538 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 6/12
[h265ize]: [debug] Running Query: ffmpeg -ss 3364.512307153846 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 7/12
[h265ize]: [debug] Running Query: ffmpeg -ss 2883.867691846154 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 8/12
[h265ize]: [debug] Running Query: ffmpeg -ss 2403.2230765384616 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 9/12
[h265ize]: [debug] Running Query: ffmpeg -ss 1922.578461230769 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 10/12
[h265ize]: [debug] Running Query: ffmpeg -ss 1441.933845923077 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 11/12
[h265ize]: [debug] Running Query: ffmpeg -ss 961.2892306153846 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 12/12
[h265ize]: [debug] Running Query: ffmpeg -ss 480.6446153076923 -i Cargo (2018).avi -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: [verbose] Mapping HE Audio streams...
[h265ize]: [verbose] Setting ffmpeg settings...
[h265ize]: [verbose] Encoding video...
[h265ize]: [debug] Running Query: ffmpeg -i Cargo (2018).avi -y -acodec copy -vcodec libx265 -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s:a:1 title="Unknown AC3 (5.1 Channel)" -metadata:s:0:1 DISPOSITION:default=1 -preset fast -x265-params crf=19: C:\Users\Drew\AppData\Local\Temp\h265ize\Cargo (2018).encoding-in-progress.mkv
[h265ize]: [debug] Error: ffmpeg exited with code 1:
    at ChildProcess.<anonymous> (C:\Users\Drew\AppData\Roaming\npm\node_modules\h265ize\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[h265ize]: ffmpeg exited with code 1:
[h265ize]: [verbose] Finished encoding at Fri, 10:49 PM (a few seconds)
[h265ize]: [debug] Finished encoding in 5.651 seconds.
[h265ize]: Folder encoding finished at Friday, March 13th 2020, 10:49:31 PM
------------------------------------------------------------------------------------------------------------------------
[h265ize]: [alert] The following videos (1) were not encoded:
        - Cargo (2018).avi: ffmpeg exited with code 1:
[h265ize]: Process exited.

**Comment by JoshuaGarrison27** [comment]
```
D:\Downloads\TestSource>h265ize -d "D:\Downloads\TestDest" -v "D:\Downloads\TestSource" --debug
[h265ize]: [debug] Log file location: D:\Downloads\TestSource\h265ize.log
[h265ize]: [alert] ffmpeg not found. Using fallback binary.
[h265ize]: [alert] ffprobe not found. Using fallback binary.
[h265ize]: [verbose] Handling keypresses...
[h265ize]: [verbose] Setting as-preset options...
[h265ize]: [debug] Video files found:
        - D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv
        - D:\Downloads\TestSource\The.O.C.S01E02.The.Model.Home.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv
        - D:\Downloads\TestSource\The.O.C.S01E04.The.Debut.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv
        - D:\Downloads\TestSource\The.O.C.S01E03.The.Gamble.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv
[h265ize]: [verbose] Folder encoding started at Saturday, April 18th 2020, 11:38:58 AM
[h265ize]: Processing The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv...
------------------------------------------------------------------------------------------------------------------------
[h265ize]: [verbose] Encoding started at Sat, 11:38 AM
[h265ize]: [debug] Path: D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv
[h265ize]: [verbose] Getting metadata...
[h265ize]: [debug] Container data:
        - duration: 00:45:06
        - size: 4.32 GB
[h265ize]: [verbose] Resolving video streams...
[h265ize]: [debug] Working on stream:
[h265ize]: [debug] Working on stream: 1
[h265ize]: [debug] Working on stream: 2
[h265ize]: [verbose] Upconverting...
[h265ize]: [debug] Upconverting 0 tracks.
[h265ize]: [verbose] Setting video bit depth...
[h265ize]: [verbose] Mapping streams...
[h265ize]: [debug] Video stream 0:0 mapped.
        - size: 1920x1080
        - codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
        - profile: High
        - bit depth: 8
[h265ize]: [alert] Audio does not have a title. Title set to "English EAC3 (Stereo)".
[h265ize]: [debug] Audio stream 0:1 mapped.
        - title: undefined
        - language: English
        - codec: ATSC A/52B (AC-3, E-AC-3)
        - channels: 2
        - profile: unknown
[h265ize]: English
[h265ize]: [alert] Subtitle does not have a title. Title set to English.
[h265ize]: [debug] Subtitle stream 0:2 mapped.
        - title: undefined
        - language: English
        - codec: SubRip subtitle
[h265ize]: [verbose] Detecting auto crop...
[h265ize]: Crop Detection: 1/12
[h265ize]: [debug] Running Query: ffmpeg -ss 2498.419384615385 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 2/12
[h265ize]: [debug] Running Query: ffmpeg -ss 2290.217769230769 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 3/12
[h265ize]: [debug] Running Query: ffmpeg -ss 2082.016153846154 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 4/12
[h265ize]: [debug] Running Query: ffmpeg -ss 1873.8145384615386 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 5/12
[h265ize]: [debug] Running Query: ffmpeg -ss 1665.6129230769232 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 6/12
[h265ize]: [debug] Running Query: ffmpeg -ss 1457.4113076923077 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 7/12
[h265ize]: [debug] Running Query: ffmpeg -ss 1249.2096923076924 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 8/12
[h265ize]: [debug] Running Query: ffmpeg -ss 1041.008076923077 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 9/12
[h265ize]: [debug] Running Query: ffmpeg -ss 832.8064615384616 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 10/12
[h265ize]: [debug] Running Query: ffmpeg -ss 624.6048461538462 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 11/12
[h265ize]: [debug] Running Query: ffmpeg -ss 416.4032307692308 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 12/12
[h265ize]: [debug] Running Query: ffmpeg -ss 208.2016153846154 -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: [alert] Output will be cropped to 1920x1072. Originally 1920x1080
[h265ize]: [verbose] Mapping HE Audio streams...
[h265ize]: [verbose] Setting ffmpeg settings...
[h265ize]: [verbose] Encoding video...
[h265ize]: [debug] Running Query: ffmpeg -i D:\Downloads\TestSource\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].mkv -y -acodec copy -vcodec libx265 -filter:v crop=1920:1072:0:4 -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s:a:1 title="English EAC3 (Stereo)" -map 0:2 -metadata:s:0:2 title=English -metadata:s:0:2 DISPOSITION:default=0 -preset fast -x265-params crf=19: C:\Users\user\AppData\Local\Temp\h265ize\The.O.C.S01E01.Pilot.[WEBDL-1080p].[x264.EAC3.2.0].[SiGMA].encoding-in-progress.mkv
[h265ize]: [debug] Error: ffmpeg exited with code 1:
    at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\h265ize\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[h265ize]: ffmpeg exited with code 1:
[h265ize]: [verbose] Finished encoding at Sat, 11:39 AM (a few seconds)
[h265ize]: [debug] Finished encoding in 2.759 seconds.
```

**Comment by Jorman** [comment]
Hi, I've a similar problem too, I don't know if is related. Under windows, I get error but under linux, the same file with same command run fine.
The command
`h265ize --debug -v -m medium -q 20 -x --aq-mode 3 --delete --stats prova.mkv`
On Windows I get this error:
```
[h265ize]: [verbose] Handling keypresses...
[h265ize]: [verbose] Setting as-preset options...
[h265ize]: Processing prova.mkv...
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[h265ize]: [verbose] Encoding started at Tue, 6:37 PM
[h265ize]: [debug] Path: prova.mkv
[h265ize]: [debug] File c:\Users\JORMAN\Videos\test\prova.mkv already exists.
[h265ize]: [verbose] Getting metadata...
[h265ize]: [debug] Container data:
	- duration: 00:02:09
	- size: 9.97 MB
[h265ize]: [verbose] Resolving video streams...
[h265ize]: [debug] Working on stream:
[h265ize]: [debug] Working on stream: 1
[h265ize]: [verbose] Upconverting...
[h265ize]: [debug] Upconverting 0 tracks.
[h265ize]: [verbose] Setting video bit depth...
[h265ize]: [verbose] Mapping streams...
[h265ize]: [debug] Video stream 0:0 mapped.
	- size: 1364x768
	- codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
	- profile: High
	- bit depth: 8
[h265ize]: [debug] Audio stream 0:1 mapped.
	- title: simple_aac_recording
	- language: Unknown
	- codec: AAC (Advanced Audio Coding)
	- channels: 2
	- profile: LC
[h265ize]: [verbose] Detecting auto crop...
[h265ize]: Crop Detection: 1/12
[h265ize]: [debug] Running Query: ffmpeg -ss 119.90769230769232 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 2/12
[h265ize]: [debug] Running Query: ffmpeg -ss 109.91538461538461 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 3/12
[h265ize]: [debug] Running Query: ffmpeg -ss 99.92307692307692 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 4/12
[h265ize]: [debug] Running Query: ffmpeg -ss 89.93076923076923 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 5/12
[h265ize]: [debug] Running Query: ffmpeg -ss 79.93846153846154 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 6/12
[h265ize]: [debug] Running Query: ffmpeg -ss 69.94615384615385 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 7/12
[h265ize]: [debug] Running Query: ffmpeg -ss 59.95384615384616 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 8/12
[h265ize]: [debug] Running Query: ffmpeg -ss 49.96153846153846 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 9/12
[h265ize]: [debug] Running Query: ffmpeg -ss 39.96923076923077 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 10/12
[h265ize]: [debug] Running Query: ffmpeg -ss 29.97692307692308 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 11/12
[h265ize]: [debug] Running Query: ffmpeg -ss 19.984615384615385 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: Crop Detection: 12/12
[h265ize]: [debug] Running Query: ffmpeg -ss 9.992307692307692 -i prova.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: [alert] Output will be cropped to 1216x608. Originally 1364x768
[h265ize]: [verbose] Mapping HE Audio streams...
[h265ize]: [verbose] Setting ffmpeg settings...
[h265ize]: [verbose] Encoding video...
[h265ize]: [debug] Running Query: ffmpeg -i prova.mkv -y -acodec copy -vcodec libx265 -filter:v crop=1216:608:4:0 -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s:0:1 DISPOSITION:default=1 -preset medium -x265-params crf=20: C:\Users\JORMAN\AppData\Local\Temp\h265ize\prova.encoding-in-progress.mkv
[h265ize]: [debug] Error: ffmpeg exited with code 1: 
    at ChildProcess.<anonymous> (C:\Users\JORMAN\AppData\Roaming\npm\node_modules\h265ize\node_modules\fluent-ffmpeg\lib\processor.js:182:22)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```
And if I try to manually run this:
`ffmpeg -i prova.mkv -y -acodec copy -vcodec libx265 -filter:v crop=1216:608:4:0 -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s:0:1 DISPOSITION:default=1 -preset medium -x265-params crf=20 C:\Users\JORMAN\AppData\Local\Temp\h265ize\prova.encoding-in-progress.mkv`
I get this error:
```
c:\Users\JORMAN\Videos\test>ffmpeg -i prova.mkv -y -acodec copy -vcodec libx265 -filter:v crop=1216:608:4:0 -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s:0:1 DISPOSITION:default=1 -preset medium -x265-params crf=20 C:\Users\JORMAN\AppData\Local\Temp\h265ize\prova.encoding-in-progress.mkv
ffmpeg version git-2020-04-20-cacdac8 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200328
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.102 / 56. 42.102
  libavcodec     58. 80.100 / 58. 80.100
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 79.100 /  7. 79.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, matroska,webm, from 'prova.mkv':
  Metadata:
    ENCODER         : Lavf58.29.100
  Duration: 00:02:09.90, start: 0.000000, bitrate: 644 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1364x768 [SAR 1:1 DAR 341:192], 30 fps, 30 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      DURATION        : 00:02:09.900000000
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : simple_aac_recording
      DURATION        : 00:02:09.892000000
[matroska @ 00000261f4935bc0] Invalid stream specifier: 0:1.
    Last message repeated 1 times
```
Any idea?
