### ISSUE TITLE
ffmpeg exited with code 1:

### ISSUE THREAD

**Issue by shervin-sa** [FallingSnow/h265ize#153]
I have just installed this on a mac osx, version 10.15.5 ( Catalina)

I am running the cmd

h265ize -v -m medium -q 20 -x --no-sao --aq-mode 3   --debug .

[h265ize]: [debug] Running Query: ffmpeg -ss 273.4892307692308 -i Video_file.mkv -y -vframes 2 -filter:v cropdetect=0.094:16:0 -map 0:0 -f null -
[h265ize]: [verbose] Mapping HE Audio streams...
[h265ize]: [verbose] Setting ffmpeg settings...
[h265ize]: [verbose] Encoding video...
[h265ize]: [debug] Running Query: ffmpeg -n 10 /usr/local/bin/ffmpeg -i Video_file.mkv -y -acodec copy -vcodec libx265 -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s:a:1 title="English AC3 (5.1 Channel)" -map 0:2 -metadata:s:0:2 DISPOSITION:default=0 -preset medium -x265-params crf=20: /var/folders/cq/xmdc6bbs30sdv_1vm_8423zr0000gp/T/h265ize/Video_file.encoding-in-progress.mkv
[h265ize]: [debug] Error: ffmpeg exited with code 1:
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/h265ize/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
[h265ize]: ffmpeg exited with code 1:
[h265ize]: [verbose] Finished encoding at Wed, 10:38 PM (a few seconds)
[h265ize]: [debug] Finished encoding in 1.15 seconds.

**Comment by igno2k** [comment]
Same here on Arch Linux.

`ffmpeg version n4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
`

**Comment by elchmartin** [comment]
just gave h265ize a shot in win10x64, experiencing the same issue ... one of you has solved the issue?

**Comment by Kazz3r24** [comment]
Still present today, mine was working until I'd updated ffmpeg to latest version 4.3-2 on Ubuntu 16 just now. Bitdepth is also being ignored (this issue isn't present running ffmpeg standalone).

**Comment by Sparkx120** [comment]
Saw this on ubuntu, I believe it is failing to escape the filenames correctly so ffmpeg exits with a `No such file or directory` error.

**Comment by Wixely** [comment]
> Saw this on ubuntu, I believe it is failing to escape the filenames correctly so ffmpeg exits with a `No such file or directory` error.

I had the same issue. When I fixed the filenames however I could see with --debug that I was getting another error.

`   [matroska @ 0000018ae96b44c0] Invalid stream specifier: 0:2.`

**Comment by sorvani** [comment]
Looks the same as I reported in April. I also just tried it on a new install of windows. Exact same issue.

Looks like this project is dead.

https://github.com/FallingSnow/h265ize/issues/150

**Comment by mikelesagitter** [comment]
Hi, I have error code 1 too but even with very simples filenames (I made a test with input.mp4, start.mp4) and got the same result. Anyway to solve this?

`[h265ize]: Processing input.mp4...
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[h265ize]: [verbose] Encoding started at Fri, 10:01 AM
[h265ize]: [verbose] Getting metadata...
[h265ize]: [verbose] Resolving video streams...
[h265ize]: [verbose] Upconverting...
[h265ize]: [verbose] Setting video bit depth...
[h265ize]: [verbose] Mapping streams...
[h265ize]: [alert] Audio does not have a title. Title set to "Unknown AAC LC (Stereo)".
[h265ize]: [verbose] Detecting auto crop...
[h265ize]: Crop Detection: 12/12
[h265ize]: [verbose] Mapping HE Audio streams...
[h265ize]: [verbose] Setting ffmpeg settings...
[h265ize]: [verbose] Encoding video...
[h265ize]: ffmpeg exited with code 1: 
[h265ize]: [verbose] Finished encoding at Fri, 10:01 AM (a few seconds)`

**Comment by fan74-f** [comment]
I had the same problem with mp4, and i don't know if my solution can help you.
I used a mkvtoolnik before the h265ize command to recreate the file with the mkv extension without the header compression... (i didn't find another way...)

**Comment by Kazz3r24** [comment]
Saw this in another issue post for the same error on this repo, this fixed it for me as well. Worth giving it a shot. If installed via npm do this.

sudo npm uninstall h265ize --global
git clone https://github.com/FallingSnow/h265ize
cd h265ize
sudo npm install --global
