### ISSUE TITLE
 ffmpeg exited with code 1 - Unable to find a suitable output format for '10'

### ISSUE THREAD

**Issue by JooJooBee666** [FallingSnow/h265ize#158]
Oddly, this used to work but now I can't use it on ANY files any longer, the above errors are all I get now.

Ubuntu 20.04

`ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100`

Here's the last few lines on the debug output log:
`[h265ize]: [debug] Running Query: ffmpeg -n 10 /usr/bin/ffmpeg -i myvideo.mkv -y -acodec copy -vcodec hevc_nvenc -c:s copy -pix_fmt yuv420p -map 0:0 -map 0:1 -metadata:s:a:1 title="English DTS DTS (5.1 Channel)" -map 0:2 -metadata:s:0:2 title=English -metadata:s:0:2 DISPOSITION:default=0 -map 0:3 -metadata:s:0:3 title=Dutch; Flemish -metadata:s:0:3 DISPOSITION:default=0 -preset fast -x265-params crf=19: /tmp/h265ize/myvideo.encoding-in-progress.mkv
[h265ize]: [debug] Error: ffmpeg exited with code 1: 
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/h265ize/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
[h265ize]: ffmpeg exited with code 1: `

If I run that query manually:
`ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Trailing options were found on the commandline.
Input #0, matroska,webm, from 'myvideo.mkv':
  Metadata:
    encoder         : libebml v0.7.9 + libmatroska v0.8.1
    creation_time   : 2012-08-22T09:02:09.000000Z
  Duration: 01:36:08.06, start: 0.000000, bitrate: 11399 kb/s
    Chapter #0:0: start 0.000000, end 520.937000
    Metadata:
      title           : 00:00:00.000
    Chapter #0:1: start 520.937000, end 841.466000
    Metadata:
      title           : 00:08:40.937
    Chapter #0:2: start 841.466000, end 1220.010000
    Metadata:
      title           : 00:14:01.466
    Chapter #0:3: start 1220.010000, end 1606.480000
    Metadata:
      title           : 00:20:20.010
    Chapter #0:4: start 1606.480000, end 1931.596000
    Metadata:
      title           : 00:26:46.480
    Chapter #0:5: start 1931.596000, end 2204.077000
    Metadata:
      title           : 00:32:11.596
    Chapter #0:6: start 2204.077000, end 2639.595000
    Metadata:
      title           : 00:36:44.077
    Chapter #0:7: start 2639.595000, end 2884.298000
    Metadata:
      title           : 00:43:59.595
    Chapter #0:8: start 2884.298000, end 3258.630000
    Metadata:
      title           : 00:48:04.298
    Chapter #0:9: start 3258.630000, end 3683.346000
    Metadata:
      title           : 00:54:18.630
    Chapter #0:10: start 3683.346000, end 3963.168000
    Metadata:
      title           : 01:01:23.346
    Chapter #0:11: start 3963.168000, end 4102.724000
    Metadata:
      title           : 01:06:03.168
    Chapter #0:12: start 4102.724000, end 4479.850000
    Metadata:
      title           : 01:08:22.724
    Chapter #0:13: start 4479.850000, end 4890.344000
    Metadata:
      title           : 01:14:39.850
    Chapter #0:14: start 4890.344000, end 5350.554000
    Metadata:
      title           : 01:21:30.344
    Chapter #0:15: start 5350.554000, end 5768.055000
    Metadata:
      title           : 01:29:10.554
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1040, SAR 1:1 DAR 24:13, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc
    Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s (default)
    Stream #0:2(eng): Subtitle: subrip
    Stream #0:3(dut): Subtitle: subrip (default)
[NULL @ 0x55a958491900] Unable to find a suitable output format for '10'
10: Invalid argument
Flemish: command not found`
I tried changing the libx265 codec on line 711 to hevc_nvenc but this did not help.  Headers are installed for NVidia CUDA.

**Edit**: I don't know WTF is wrong with github code blocks totally ignoring line breaks.  Let me know if you need it without.  What a mess.  FAIL.

**Comment by citruz** [comment]
Same error here

**Comment by citruz** [comment]
I was able to fix the problem by using the lastest version from git instead of npm.
```
sudo npm uninstall h265ize --global
git clone https://github.com/FallingSnow/h265ize
cd h265ize
sudo npm install --global
```
I guess #136 fixed it.

**Comment by JooJooBee666** [comment]
I'm not sure which commit fixed it but I can confirm installing from git instead of npm fixed it for me as well.

**Comment by OutsmartinTech** [comment]
Just wanted to chime in that I also had this error and using the git install instead of npm fixed it for me as well.

**Comment by zmiguel** [comment]
I was also having this error, installed with git and now I'm getting file not found because FFmpeg thinks the file is on /home/username/h265/* instead of the absolute path I tell it.

**Comment by JohnDelisle** [comment]
@zmiguel - do this instead, it installs to /opt, which all users should have access to.  Tested on Ubuntu 20.10.

```
sudo npm uninstall h265ize --global
cd /opt
sudo git clone https://github.com/FallingSnow/h265ize
cd h265ize
sudo npm install --global
```

**Comment by traverseda** [comment]
This seems to break support for `--delete`...

**Comment by xingfanxia** [comment]
> This seems to break support for `--delete`...
> 
> ```
> [h265ize]: [verbose] Encoding started at Sat, 5:14 PM
> [h265ize]: [verbose] Running stage: Initialize filesystem
> Unhandled rejection Error: ENOENT: no such file or directory, unlink '/home/shared/movies/h265/bigbuckbunny.mkv'
>     at Object.unlinkSync (fs.js:956:3)
>     at /opt/h265ize/lib/classes/video.js:1259:20
>     at arrayEach (/opt/h265ize/node_modules/lodash/lodash.js:516:11)
>     at Function.forEach (/opt/h265ize/node_modules/lodash/lodash.js:9368:14)
>     at /opt/h265ize/lib/classes/video.js:1258:15
>     at Video.cleanUp (/opt/h265ize/lib/classes/video.js:1257:16)
>     at Video.stop (/opt/h265ize/lib/classes/video.js:1252:21)
>     at Encoder.removeVideo (/opt/h265ize/lib/classes/encoder.js:176:19)
>     at EventEmitter.<anonymous> (/opt/h265ize/lib/classes/encoder.js:147:23)
>     at EventEmitter.emit (events.js:198:13)
>     at /opt/h265ize/lib/classes/video.js:1182:26
> From previous event:
>     at Video.start (/opt/h265ize/lib/classes/video.js:1174:34)
>     at Encoder.loop (/opt/h265ize/lib/classes/encoder.js:151:15)
>     at Encoder.start (/opt/h265ize/lib/classes/encoder.js:73:18)
>     at /opt/h265ize/h265ize:255:25
> ```

Having same issue here..
