### ISSUE TITLE
stdin error in docker

### ISSUE THREAD

**Issue by kgelinas** [FallingSnow/h265ize#68]
I'm having issues when trying to run this in docker (kubernetes to be more specific but this should not be different) which does not use tty by default

maybe you should check for tty
with something like this

```
if (process.stdin.isTTY){
        process.stdin.setRawMode(true);
      }
```

```
[h265ize]: [verbose] Handling keypresses...
[h265ize]:
        - message: process.stdin.setRawMode is not a function
        - stack: TypeError: process.stdin.setRawMode is not a function
    at /usr/local/lib/node_modules/h265ize/h265ize:485:23
    at h265ize.handleKeypress (/usr/local/lib/node_modules/h265ize/h265ize:453:12)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Object.h265ize.runCli (/usr/local/lib/node_modules/h265ize/h265ize:47:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/h265ize/h265ize:1701:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
        - __stackCleaned__: true
[h265ize]: [verbose] Cleaning up temp files...
[h265ize]: Process exited.
```

**Comment by FallingSnow** [comment]
After adding the condition for `isTTY` does it run perfectly?

**Comment by kgelinas** [comment]
no
I believe all the keypress event won't work
I used a workaround with this command
script --return -c "[executable string]" /dev/null

this seem to work
