### ISSUE TITLE
installation error on opensuse 12.3

### ISSUE THREAD

**Issue by egorks** [FallingSnow/h265ize#74]
hi! 

i am running opensuse 12.3 with xen kernel:
3.7.10-1.45-xen #1 SMP Tue Dec 16 20:27:58 UTC 2014 (4c885a1) x86_64 x86_64 x86_64 

during installation i get following output:

```
1459][root@term01:~]# npm install h265ize --global
npm http GET https://registry.npmjs.org/h265ize
npm http 304 https://registry.npmjs.org/h265ize
npm http GET https://registry.npmjs.org/h265ize/-/h265ize-0.4.3-r2.tgz
npm http 200 https://registry.npmjs.org/h265ize/-/h265ize-0.4.3-r2.tgz
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/ffmpeg-static
npm http GET https://registry.npmjs.org/ffprobe-static
npm http GET https://registry.npmjs.org/filesize
npm http GET https://registry.npmjs.org/fluent-ffmpeg
npm http GET https://registry.npmjs.org/fs-extra
npm http GET https://registry.npmjs.org/hasbin
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/mathjs
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/moment-duration-format
npm http GET https://registry.npmjs.org/optional
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/recursive-readdir
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/yargs
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/bluebird
npm ERR! Error: No compatible version found: colors@'^1.1.2'
npm ERR! Valid install targets:
npm ERR! ["0.3.0","0.5.0","0.5.1","0.6.0","0.6.0-1","0.6.1","0.6.2","1.0.0","1.0.1","1.0.2","1.0.3","1.1.0","1.1.1","1.1.2"]
npm ERR!     at installTargetsError (/usr/lib64/node_modules/npm/lib/cache.js:553:10)
npm ERR!     at /usr/lib64/node_modules/npm/lib/cache.js:477:15
npm ERR!     at saved (/usr/lib64/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/lib64/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.7.10-1.45-xen
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "h265ize" "--global"
npm ERR! cwd /root
npm ERR! node -v v0.8.12
npm ERR! npm -v 1.1.63
npm http 304 https://registry.npmjs.org/fs-extra
npm http 304 https://registry.npmjs.org/ffmpeg-static
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/hasbin
npm http 200 https://registry.npmjs.org/filesize
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/optional
npm http 304 https://registry.npmjs.org/ffprobe-static
npm http 304 https://registry.npmjs.org/mathjs
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/moment-duration-format
npm http 304 https://registry.npmjs.org/yargs
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/recursive-readdir
npm http 304 https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/fluent-ffmpeg
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
[1459][root@term01:~]# 

```

i attached the npm log file as well.
as newbie i cannot understand whether its my mistake or some bug?..

[npm-debug.txt](https://github.com/FallingSnow/h265ize/files/555886/npm-debug.txt)

**Comment by FallingSnow** [comment]
I'm not sure but it looks like you are using a very old version of npm and node. Try updating both npm and node, then try to reinstall.

**Comment by egorks** [comment]
opensuse 13.1 works with it out-of-the-box (meaning installations are from official repos). however, i did not try this with xen kernel yet; only with default.
will test some more...

**Comment by FallingSnow** [comment]
Strange, but at least it works. Let me know if you figure out what your issue was.
